start cmd.exe /C "src\REstate.Services.Auth\bin\Release\REstate.Services.Auth.exe start"
start cmd.exe /C "src\REstate.Services.Core\bin\Release\REstate.Services.Core.exe start"
start cmd.exe /C "src\REstate.Services.Chrono\bin\Release\REstate.Services.Chrono.exe start"
start cmd.exe /C "src\REstate.Services.ChronoConsumer\bin\Release\REstate.Services.ChronoConsumer.exe start"
start cmd.exe /C "src\REstate.Service.AdminUI\bin\Release\REstate.Services.AdminUI.exe start"