start cmd.exe /C "src\REstate.Services.Auth\bin\Release\REstate.Services.Auth.exe stop"
start cmd.exe /C "src\REstate.Services.Core\bin\Release\REstate.Services.Core.exe stop"
start cmd.exe /C "src\REstate.Services.Chrono\bin\Release\REstate.Services.Chrono.exe stop"
start cmd.exe /C "src\REstate.Services.ChronoConsumer\bin\Release\REstate.Services.ChronoConsumer.exe stop"
start cmd.exe /C "src\REstate.Service.AdminUI\bin\Release\REstate.Services.AdminUI.exe stop"